services:
  - type: web
    name: voice-video-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_TOKEN
        value: 7958617447:AAEi_efhiSUGwwxOJcUSDlJ3qCCofcKrVsA
